name: Code linter

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
    code-style-check:
      name: run linter
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Lint codebase
          uses: github/super-linter@v4
          env:
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}