name: Run Tests

on:
  push:
    branches: [main]
  pull-request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Setup maven
        uses: stCarolas/setup-maven@4.4
        with:
          maven-version: 2.7.8

      - name: Tests and Coverage
        run: mvn clean install